spring:
  cloud:
    gateway:
      routes:
        - id: firstSampleService
          uri: lb://firstSampleService/
          predicates:
            - Path=/firstService/**
            - Method=POST, GET
        - id: secondSampleService
          uri: lb://secondSampleService/
          predicates:
            - Path=/name/**