
spring:
  cloud:
    gateway:
      routes:
        - id: firstSampleService
          uri: lb://FIRSTSAMPLESERVICE/
          predicates:
            - Path=/firstService/**
            - Method=POST, GET
          filters:
            - RewritePath=/firstService/(?<path>.*),/$\{path}
        - id: secondSampleService
          uri: lb://SECONDSAMPLESERVICE/
          predicates:
            - Path=/name/**
          filters:
            - RewritePath=/name/(?<path>.*),/$\{path}
        - id: apiManageService
          uri: lb://APIMANAGESERVICE/
          predicates:
            - Path=/api/**
            - Method=POST, GET
          filters:
            - RewritePath=/api/(?<path>.*),/$\{path}
