spring:
  cloud:
   gateway:
     routes:
      - id: testSecondService
        uri: localhost:1112
        predicates:
         - Path=/test/second/service/**
         - Method=get
        filters:
         - RewritePath=/test/second/service/(?<path>.*),/$\{path}
      - id: testFourth
        uri: lb://TESTFOURTH/
        predicates:
         - Path=/test/fourth/service/**
         - Method=get
        filters:
         - RewritePath=/test/fourth/service/(?<path>.*),/$\{path}
      - id: testFifth
        uri: lb://TESTFIFTH/
        predicates:
         - Path=/test/fifth/service/**
         - Method=get
        filters:
         - RewritePath=/test/fifth/service/(?<path>.*),/$\{path}
      - id: testEigth
        uri: localhost:1118
        predicates:
         - Path=/test/eigth/**
         - Method=get
        filters:
         - RewritePath=/test/eigth/(?<path>.*),/$\{path}
      - id: testNinth
        uri: lb://TESTNINTH/
        predicates:
         - Path=/test/ninth/service/**
         - Method=post
        filters:
         - RewritePath=/test/ninth/service/(?<path>.*),/$\{path}
      - id: testTenth
        uri: localhost:1110
        predicates:
         - Path=/test/tenth/**
         - Method=get
        filters:
         - RewritePath=/test/tenth/(?<path>.*),/$\{path}
      - id: testEleventh
        uri: lb://TESTELEVENTH/
        predicates:
         - Path=/test/eleventh/**
         - Method=post
        filters:
         - RewritePath=/test/eleventh/(?<path>.*),/$\{path}
      - id: testFourteenth
        uri: localhost:1124
        predicates:
         - Path=/test/tourteenth/service/**
         - Method=get
        filters:
         - RewritePath=/test/tourteenth/service/(?<path>.*),/$\{path}
      - id: testFifteenth
        uri: localhost:1125
        predicates:
         - Path=/test/fiftheenth/service/**
         - Method=post
        filters:
         - RewritePath=/test/fiftheenth/service/(?<path>.*),/$\{path}
      - id: testSixteenth
        uri: lb://TESTSIXTEENTH/
        predicates:
         - Path=/test/sixteenth/service/**
         - Method=get
        filters:
         - RewritePath=/test/sixteenth/service/(?<path>.*),/$\{path}
