spring:
  cloud:
    gateway:
      routes:
        - id: firstSampleService
          uri: lb://firstSampleService/
          predicates:
            - Path=/firstService2/**
            - Method=POST, GET
