spring:
  application:
    name: firstSampleService
  profiles:
    active: defalut
  config:
    activate:
      on-profile: dev
    name: firstSampleService
    profile: dev
    import: optional:config-server:http://localhost:8888
    use-legacy-processing: true


myconfig:
  name: jhpark222232323232
