spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: firstSampleService
          uri: lb://firstSampleService/
          predicates:
            - Path=/firstService/**
            - Method=POST, GET
