spring:
  application:
    name: firstSampleService
  profiles:
    active: dev
    
myconfig:
  name: jhpark22223232323222ss

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enable: true